trigger:
  branches:
    include:
      - dev
  paths:
    include:
      - chatbot-saas-platform/backend/src/LiveAgentService**
pool:
  name: ubuntu-22.04

variables:
  workingDirectory: 'chatbot-saas-platform/backend/src/LiveAgentService'
  artifactName: 'LiveAgentService'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET 9 SDK'
    inputs:
      packageType: 'sdk'
      version: '9.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - script: |
      dotnet --info
      which dotnet
    displayName: "Verify .NET SDK in use"
  - script: |
      dotnet restore chatbot-saas-platform/backend/src/LiveAgentService/LiveAgentService.csproj
    displayName: 'Restore with dotnet CLI'

  - task: DotNetCoreCLI@2
    displayName: 'Build project'
    inputs:
      command: 'build'
      projects: 'chatbot-saas-platform/backend/src/LiveAgentService/LiveAgentService.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Publish project'
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: 'chatbot-saas-platform/backend/src/LiveAgentService/LiveAgentService.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(outputDir)'
      zipAfterPublish: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish build artifact'
    inputs:
      PathtoPublish: '$(outputDir)'
      ArtifactName: 'LiveAgentService'
      publishLocation: 'Container'
