trigger:
  branches:
    include:
      - dev
  paths:
    include:
      - chatbot-saas-platform/backend/src/ApiGateway/**
pool:
  name: ubuntu-22.04

variables:
  buildConfiguration: 'Release'
  outputDir: '$(Build.ArtifactStagingDirectory)/ApiGateway_publish'
  workingDirectory: 'chatbot-saas-platform/backend/src/ApiGateway'
  artifactName: 'ApiGateway'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET 9 SDK'
    inputs:
      packageType: 'sdk'
      version: '9.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: DotNetCoreCLI@2
    displayName: 'Publish project'
    inputs:
      command: 'publish'
      publishWebProjects: true
      projects: 'chatbot-saas-platform/backend/src/ApiGateway/ApiGateway.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(outputDir) /p:GeneratePackageOnBuild=false'
      zipAfterPublish: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish build artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'ApiGateway'
      publishLocation: 'Container'