trigger:
  branches:
    include:
      - dev

pool:
  name: ubuntu-22.04

variables:
  workingDirectory: 'chatbot-saas-platform/backend/src/ApiGateway'
  artifactName: 'ApiGateway'
  buildConfiguration: 'Release'
  outputDir: '$(Build.ArtifactStagingDirectory)/arif-apigateway'  

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET 9 SDK'
    inputs:
      packageType: 'sdk'
      version: '9.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: DotNetCoreCLI@2
    displayName: 'Restore NuGet packages'
    inputs:
      command: 'restore'
      projects: 'chatbot-saas-platform/backend/src/ApiGateway/ApiGateway.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Build project'
    inputs:
      command: 'build'
      projects: 'chatbot-saas-platform/backend/src/ApiGateway/ApiGateway.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Publish project'
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: 'chatbot-saas-platform/backend/src/ApiGateway/ApiGateway.csproj'
      arguments: >
        --configuration $(buildConfiguration)
        --output $(outputDir)
        /p:PublishSingleFile=false
      zipAfterPublish: false
  - script: |
      dotnet publish src/ApiGateway/ApiGateway.csproj -c Release -o $(outputDir)
    displayName: 'Publish .NET project'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish build artifact'
    inputs:
      PathtoPublish: '$(outputDir)'
      ArtifactName: 'arif-apigateway'
      publishLocation: 'Container'
