trigger:
  branches:
    include:
      - dev

pool:
  name: ubuntu-22.04

variables:
  workingDirectory: 'chatbot-saas-platform/backend/src/AIOrchestrationService'
  artifactName: 'AIOrchestrationService'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET 9 SDK'
    inputs:
      packageType: 'sdk'
      version: '9.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: DotNetCoreCLI@2
    displayName: 'Restore NuGet packages'
    inputs:
      command: 'restore'
      projects: 'chatbot-saas-platform/backend/src/AIOrchestrationService/AIOrchestrationService.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Build project'
    inputs:
      command: 'build'
      projects: 'chatbot-saas-platform/backend/src/AIOrchestrationService/AIOrchestrationService.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Publish project'
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: 'chatbot-saas-platform/backend/src/AIOrchestrationService/AIOrchestrationService.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(outputDir)'
      zipAfterPublish: false

  - task: PublishBuildArtifacts@1
    displayName: 'Publish build artifact'
    inputs:
      PathtoPublish: '$(outputDir)'
      ArtifactName: 'AIOrchestrationService'
      publishLocation: 'Container'
