version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: arif-platform-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - arif-platform-network

  redis:
    image: redis:7-alpine
    container_name: arif-platform-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - arif-platform-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: arif-platform-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - arif-platform-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: arif-platform-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - arif-platform-network

volumes:
  sqlserver_data:
  redis_data:
  rabbitmq_data:
  qdrant_data:

networks:
  arif-platform-network:
    driver: bridge
