trigger:
  branches:
    include:
      - dev  
  paths:
    include:
      - chatbot-saas-platform/frontend/chatbot-widget/**
pool:
  name: ubuntu-22.04

variables:
  workingDirectory: 'chatbot-saas-platform/frontend/chatbot-widget'
  artifactName: 'chatbot-widget'

steps:
#  Use Node 22
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Use Node.js 22'

- script: |
    rm -rf dist build .cache .vite .next node_modules package-lock.json
    npm cache clean --force
    npm install
  workingDirectory: $(workingDirectory)
  displayName: 'Clean workspace and install'

# Build React app
- script: npx vite build --mode staging
  workingDirectory: $(workingDirectory)
  displayName: 'Build React app'

# Publish build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(workingDirectory)/dist'
    ArtifactName: $(artifactName)
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'
