trigger:
  branches:
    include:
      - dev  
  paths:
    include:
      - chatbot-saas-platform/frontend/chatbot-widget/**
pool:
  name: ubuntu-22.04

variables:
  workingDirectory: 'chatbot-saas-platform/frontend/chatbot-widget'
  artifactName: 'chatbot-widget'

steps:
#  Use Node 22
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Use Node.js 22'

# Install dependencies
- script: npm install
  workingDirectory: $(workingDirectory)
  displayName: 'Install NPM dependencies'

# Build React app
- script: npm run build:staging
  workingDirectory: $(workingDirectory)
  displayName: 'Build React app'

# Publish build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(workingDirectory)/dist'
    ArtifactName: $(artifactName)
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'
